import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { BrowserRouter } from "react-router-dom";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>SWAG Tech </title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
		</>
	);
};

export default Home;
